version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
  frontend:
    build: ../frontend/deaddrop/.
    ports:
      - "5173:5173"
    expose:
      - "5173"