# Generated by Django 4.2.7 on 2024-04-12 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_results", "0012_taskresult_task_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the agent.", max_length=100
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="The version for this agent.", max_length=100
                    ),
                ),
                (
                    "package_file",
                    models.FileField(
                        help_text="The original agent package file.", upload_to="agents"
                    ),
                ),
                (
                    "package_path",
                    models.FilePathField(
                        allow_files=False,
                        allow_folders=True,
                        help_text="The directory in `packages/agents` where the agent's files have been unpackaged, with metadata generated.",
                        path="packages/agents",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("hostname", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=32, null=True)),
                ("is_virtual", models.BooleanField()),
                ("agent_cfg", models.JSONField(blank=True, null=True)),
                ("protocol_state", models.JSONField(blank=True, null=True)),
                (
                    "payload_file",
                    models.FileField(
                        blank=True,
                        help_text="The original payload bundle.",
                        null=True,
                        upload_to="payloads",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="endpoints",
                        to="backend.agent",
                    ),
                ),
                (
                    "connections",
                    models.ManyToManyField(
                        blank=True, null=True, to="backend.endpoint"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the protocol.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "package_file",
                    models.FileField(
                        help_text="The original protocol package file.",
                        upload_to="protocols",
                    ),
                ),
                (
                    "package_path",
                    models.FilePathField(
                        allow_files=False,
                        allow_folders=True,
                        help_text="The directory in `packages/protocols` where the protocol's files have been unpackaged, with metadata generated.",
                        path="packages/protocols",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("payload", models.JSONField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("CMD_RESPONSE", "command_response"),
                            ("CMD_REQUEST", "command_request"),
                            ("LOG_BUNDLE", "log_bundle"),
                            ("HEARTBEAT", "heartbeat"),
                        ],
                        max_length=50,
                    ),
                ),
                ("digest", models.BinaryField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages_destinations",
                        to="backend.endpoint",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages_sources",
                        to="backend.endpoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=32, null=True)),
                ("level", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField()),
                ("data", models.TextField()),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="backend.endpoint",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="django_celery_results.taskresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="files")),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="django_celery_results.taskresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "credential_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credential_type", models.CharField(max_length=32)),
                ("credential_value", models.CharField(max_length=1023)),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credentials",
                        to="django_celery_results.taskresult",
                    ),
                ),
            ],
        ),
    ]
