# Generated by Django 4.2.7 on 2024-04-12 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_alter_message_message_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credential",
            name="id",
        ),
        migrations.RemoveField(
            model_name="file",
            name="id",
        ),
        migrations.AddField(
            model_name="credential",
            name="credential_id",
            field=models.UUIDField(
                default=uuid.uuid4, null=True
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="file_id",
            field=models.UUIDField(
                default=uuid.uuid4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="credential_value",
            field=models.CharField(max_length=1023),
        ),
    ]
