# Generated by Django 4.2.7 on 2024-04-12 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_populate_cred_file_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="credential_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
